name: Teste Comentário Ponto no PR

on:
  pull_request:
    types: [opened]

jobs:
  comentar-ponto:
    runs-on: ubuntu-latest
    steps:
      - name: Adiciona ponto no PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;

            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ".."
            });
