name: PR Checklist

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  add_checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Add checklist to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const checklist = `
  ### ✅ Checklist obrigatório para merge

  - [ ] O código foi testado localmente?
  - [ ] O código está coberto por testes automatizados?
  - [ ] A documentação foi atualizada?
  - [ ] A revisão foi feita por outro desenvolvedor?
  
  > Marque todos os itens antes de aprovar este PR.
  `;
  
  const prNumber = context.payload.pull_request.number;
  
  const existingComments = await github.rest.issues.listComments({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: prNumber
  });
  
  const checklistAlreadyExists = existingComments.data.find(comment =>
    comment.body && comment.body.includes("✅ Checklist obrigatório para merge")
  );
  
  if (!checklistAlreadyExists) {
    await github.rest.issues.createComment({
      issue_number: prNumber,
      owner: context.repo.owner,
      repo: context.repo.repo,
      body: checklist
    });
  }
